### ISSUE TITLE
Used the instructions from this repo but can't run docker in workspace 

### ISSUE THREAD

**Issue by hanfi** [gitpod-io/gitpod-eks-guide#25] opened 2021-09-28 20:56 UTC
### Bug description

hello i followed the instructions on installing on eks using this repo,

everything works as it's supposed to be but when i try custom image on .gitpod.yml or simply run a "docker run -ti ubuntu" on the workspace terminal, i got this error : 

docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: operation not permitted: unknown.
ERRO[0004] error waiting for container: context canceled 

i tried rebuilding the builder image with different tags but can't make it work :'( 

### Steps to reproduce

make install this repository then create a workspace and try to run a container 

### Expected behavior

container starts and can use custom images on workspace 

### Example repository

have the issue with this repo:
https://github.com/gitpod-io/template-docker-compose

**Comment by szab100** [comment] 2021-10-01 19:40
I am having similar issues running anything in Docker after deployment (installed 2 days ago at 442119fca4c2ee7cefe57e2057be5ffee6256fdf using the west-2 region's AMI "ami-0a9aa973650d0c831"). Tried with both the latest workspace-full base having Docker v20.* and older tags having Docker v19.*.

Here is my comment with the exact outputs on the Docker v20 issue, https://github.com/gitpod-io/gitpod/issues/3051#issuecomment-932460520

**Comment by aledbf** [comment] 2021-10-01 21:16
@szab100 I need to release a new version of the AMI and gitpod images. The `procfd` mount issue is already fixed in main.
I hope I can release an update next week. (I am swamped right now)

**Comment by szab100** [comment] 2021-10-02 02:11
@aledbf Thank you for the quick reply! Next week would be awesome, but sure I understand you are super busy. One additional note for this is that I have also tried to run minikube / k3s / kind inside the workspace (on saas gitpod.io as docker doesn't work on my aws install), and those are failing with mount issues similar to the procfd with podman above:

`mounting "cgroup" to rootfs at "/sys/fs/cgroup" caused: operation not permitted: unknown.`

Can this be because of some missing securityContext capabilities on the ws-<..> pod, eg SYS_ADMIN? I know it is a whole different story than what this bug is about.. [one of our projects](https://github.com/argoproj-labs/argo-cloudops) has argo workfows as a dependency and my colleague is going to give a speech on KubeCon about it.. It would be nice to give the project GitPod support (on gitpod.io, not our aws deployment), so interested developers could quickly have a dev environment up & running.. but most probably this can't happen as KubeCon is less than 2 weeks away..

Either way, we need this to get fixed regardless of KubeCon, and even if local k8s support won't be possible, this docker issue is blocking us from proposing gitpod as a (self-hosted) cloud-ide solution at the company.

**Comment by aledbf** [comment] 2021-10-02 20:20
> One additional note for this is that I have also tried to run minikube / k3s / kind inside the workspace

This is still not possible. Please follow https://github.com/gitpod-io/gitpod/issues/4889
Some of the restrictions are related to the user namespace where the workspace run. Please check the [feature description](https://github.com/gitpod-io/gitpod/pull/2048)

> and those are failing with mount issues similar to the procfd with podman above:

Right now containerd is a hard requirement and there is no support for podman.

**Comment by szab100** [comment] 2021-10-04 00:50
Thank you @aledbf, Lorenzo's workaround from [this issue](https://github.com/gitpod-io/gitpod/issues/4889) helped me a lot! I made a [fork](https://github.com/szab100/gitpod-k3s) where the initial workspace build time is greatly reduced by using a pre-baked middle-layer workspace image that has QEMU installed and the initial VM root filesystem fully baked.

Certainly not perfect, mostly b/c qemu is slow to start and has quite a big overhead (it can only run in full sw-emulation mode, it would need '/dev/kvm' passthrough from the node), but seems to be a great workaround for running a local k8s cluster, until we can get full support for 'kind'.

Hope to see your fixes for Docker on the AWS deployment soon. Thanks!

**Comment by szab100** [comment] 2021-10-21 21:45
> 
> Do you mean traffic from inside the VPC?

Yes, the internal LB / ingress is having assgined IPs from the cluster's VPC subnets of each AZs. I needed to add the VPC's overall CIDR (192.168.0.0/16 in my case) into LoadBalancerSourceRanges or directly to its SecurityGroup to let the pods reach it.

OK sure I understand if websockets have issues through LBs, while I personally had no such issues. If the connection drops are limited to Ingress changes, I think that's normal and should be expected, providing reasonable client-side resiliency should be enough to handle those. But I understand there could be various issues with other providers' exotic ingress controllers that can cause bigger disruptions.

Still, even just mentioning this alternative deployment option as a less- or not-supported one might help increasing adoption, in case people are not allowed to expose NodePorts on their clusters directly due to internal policies. So far everyone else I have seen from the community experimenting with ingresses with Gitpod eventually gave up and it took me several days to come up with this workaround. So let me know if you guys need any more details, I am happy to share more details or contribute with a howto (even the CoreDNS part is very simple, just editing a configmap).

**Comment by szab100** [comment] 2021-11-08 21:38
Hi @aledbf, going back to the original topic in this issue, can we have a fix for this? I track the new installer's milestone, but it progresses slowly.. which is fine for something new, but this is an important feature that is currently broken on AWS installs.. and if I understood correctly, it has nothing to do with the installer itself, but the used AMI images & possibly ws pods configuration instead. I was planning to showcase Gitpod self-hosted on our bi-annual hackathon week and push for company-wide adoption, but this seems to be a major blocker. I see others are waiting for this as well.

**Comment by aledbf** [comment] 2021-11-08 21:49
@szab100 last week we merged the refactoring I mentioned in a previous comment https://github.com/gitpod-io/gitpod/pull/6462
With this change, we reduced the median startup time by half and got instant port exposure (no more waiting because “port was not found”) and massively reduced load on the API server.

About the original issue, we need to release a new version. That's it. The problem is the self-hosted release implies too apply too many changes, and the reason why we need to wait for the installer. Right now, the installer is running for GKE with internal dependencies. By the end of the week will be ready for external ones (registry and DB). With that done, the idea is to update the EKS and AKS guides.

I am sorry for the delay. We cannot tackle all the fronts simultaneously.

**Comment by szab100** [comment] 2021-11-09 03:20
@aledbf Awesome, no worries, thank you for the quick update! I love to see there is progress, sorry I just could not connect these pieces like you just did, it makes complete sense now and I cant wait to see these performance improvements as well. So you are saying GCP might be completed this week. Hope it's relatively quick to adapt it to EKS thereafter.

**Closed** 2021-12-01 16:45 UTC
Labels: bug
